{
  "DESIGN_NAME": topSystolicArray,
  "VERILOG_FILES": dir::*.sv,
  "CLOCK_PERIOD": 25,
  "CLOCK_PORT": i_clk,
  "DIE_AREA": [0, 0, 250, 450],
  "PL_TARGET_DENSITY_PCT": 85,
  "FP_SIZING": absolute,
}