{
  "DESIGN_NAME": heichips25_systolicArray,
  "VERILOG_FILES": dir::heichips25_systolicArray.sv,
  "CLOCK_PORT": clk,
  "CLOCK_PERIOD": 10,
  "FP_SIZING": absolute,
  "DIE_AREA": [0, 0, 450, 200],
}
